### ISSUE TITLE
Decode all HTML entities.

### ISSUE THREAD

**Issue by alexmacarthur** [alexmacarthur/wp-complete-open-graph#9]
Some HTML entities (like certain quotes) are not being decoded properly.

**Comment by tazotodua** [comment]
maybe that's strange, that Facebook doesnt parse &#smth;  type of words into symbols itself, which creating the "share dialog" output.

**Comment by alexmacarthur** [comment]
Agreed -- thanks for identifying that issue & letting me know.

**Comment by alexmacarthur** [comment]
This issue is resolved by version 3.0.1: https://github.com/alexmacarthur/wp-complete-open-graph/releases/tag/3.0.1
